# CMake 格式化规则
line_width: 100
tab_size: 4
use_tabchars: False
dangle_parens: False
max_subgroups_hwrap: 2
commands_case: lower
keywords_case: upper
force_spaces: True
tight_list: False
space_before_paren: True
